### ISSUE TITLE
Can not show the logs in Installer v2.2.4

### ISSUE THREAD

**Issue by Howard20181** [solohsu/XposedInstaller#3]
###### Include the following:
 - Xposed Version: `0.3.1.7` 
 - Xposed Systemless
 - Device OS version: `8.0 MIUI10.2`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi 5`
 - Material Xposed Installer version: `2.2.4`
 
###### Reproduction Steps

1. Start the Installer from Launcher
2. open the Module Logs page

###### Expected Result
Show the logs.

###### Actual Result
Can not read log (Permission denied)
including verbose logs
###### system log:
[logcat_system1.log](https://github.com/solohsu/XposedInstaller/files/2994299/logcat_system1.log)
[logcat_system.log](https://github.com/solohsu/XposedInstaller/files/2994301/logcat_system.log)

**Comment by Howard20181** [comment]
@solohsu

**Comment by Fylax** [comment]
Can you please verify that it is installed in internal memory?

**Comment by Howard20181** [comment]
> Can you please verify that it is installed in internal memory?

The phone I own doesn't have a TF card slot, so it can only install in internal storage.
I've tried to convert it to a system app, but still have this problem.

**Comment by Howard20181** [comment]
Fit in sandhook 3.1.8 beta 8
