### ISSUE TITLE
3

### ISSUE THREAD

**Issue by zipxxx1** [solohsu/XposedInstaller#7]
###### Include the following:
 - Xposed Version: `85` 
 - [ ] Xposed Systemless
 - Device OS version: `6.0.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 5`
 - Material Xposed Installer version: `14/09/2016`
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by MlgmXyysd** [comment]
Android Marshmallow use original Xposed.
